# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20171119_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
